name: Docker file CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: cadd-md:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image - Check installed packages
        run: |
          docker run --rm cadd-md:latest bash -c "command -v gmx && command -v vina && command -v Multiwfn"

      - name: Test image - Check Python packages
        run: |
          docker run --rm cadd-md:latest bash -c "pip list | grep -e gmx_MMPBSA -e DuIvyTools"

      - name: Test image - Check NVIDIA capabilities
        run: |
          docker run --rm cadd-md:latest bash -c "nvidia-smi || echo 'NVIDIA drivers not available in CI environment'"
